version: '3'

services:
  back:
    image: melissapanduro/chatbot_docker
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_KEY: ${API_KEY} 
  front:
    image: melissapanduro/front_docker
    ports:
      - "4200:4200"
    environment:
      API_BACKEND: ${API_BACKEND}
    depends_on:
      - back