# consultar versión de minikube
minikube version

# 1iniciar clúster kubernetes
minikube start

# listar namespace
kubectl get namespace
kubectl get ns

# crear un namespace "hernan" por comando
kubectl create namespace hernan

# crear un namespace "hernan" por comando y un "namespace.yml"
kubectl apply -f namespace.yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: hernan
---

# consultar namespace en uso por "default"
kubectl config view --minify | grep namespace

# 3cambiar un namespace en uso por "default" a "hernan"
kubectl config set-context --current --namespace=melissa

# consultar todos los recursos de un namespace "hernan"
kubectl get all -n hernan

# consultar todos los recursos y secret de un namespace "hernan"
kubectl get all,secrets -n melissa

# listar services del namespace "hernan"
minikube service api-gpt-be -n melissa
minikube service list

# probar el microservicio dentro del clúster con curl
curl http://192.168.49.2:30001/api/active
curl http://192.168.49.2:30001/api/id/1

# 6crear un túnel de puerto la máquina local (host) y el clúster de Kubernetes
kubectl port-forward service/api-gpt-be 8085:30001
kubectl port-forward service/api-gpt-frontend 4200:30002
# ver los logs del pod (logs del proyecto)
kubectl logs nombre-pod