# 2kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prs-be
  namespace: melissa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prs-be
  template:
    metadata:
      labels:
        app: prs-be
    spec:
      containers:
      - name: prs-be
        image: melissapanduro/prsback  # Reemplaza con tu imagen Docker del backend
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials                # Nombre del Secret
              key: DATABASE_URL                         # Clave dentro del Secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_PASSWORD


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prs-frontend
  namespace: melissa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prs-frontend
  template:
    metadata:
      labels:
        app: prs-frontend
    spec:
      containers:
      - name: prs-frontend
        image: melissapanduro/prsfront # Reemplaza con tu imagen Docker del frontend
        env:
        - name: API_BACKEND
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: API_BACKEND  # La clave en el Secret para API_BACKEND
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials                # Nombre del Secret
              key: DATABASE_URL                         # Clave dentro del Secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_PASSWORD
