apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: melissa
spec:
  selector:
    app: frontend
  ports:
    - port: 30006 
      targetPort: 4200 
      nodePort: 30006 
  type: NodePort       