# 4kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: melissa
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpvMGp6SHZPY2x5aDdAZXAtb2xkLXN1cmYtYTViMXpqb2kudXMtZWFzdC0yLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZQ==    # en Base64
  DATABASE_USERNAME: bmVvbmRiX293bmVy   # en Base64
  DATABASE_PASSWORD: bzBqekh2T2NseWg3  # en Base64
  API_BACKEND: aHR0cHM6Ly9zaWx2ZXItd2FmZmxlLXBqZzY3N3d2cHA2amY2NjZyLTgwODUuYXBwLmdpdGh1Yi5kZXYvYXBpL3Byb2R1Y3Rvcw==