# 4kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: melissa
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpvMGp6SHZPY2x5aDdAZXAtb2xkLXN1cmYtYTViMXpqb2kudXMtZWFzdC0yLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZQ==    # en Base64
  DATABASE_USERNAME: bmVvbmRiX293bmVy   # en Base64
  DATABASE_PASSWORD: bzBqekh2T2NseWg3  # en Base64
  #RAPIDAPI_KEY: MmNiNjMyYjJjOW1zaDc0OTNhNWFmZmM2ODNlOXAxZDFmYzNqc241ZjdmNmRiYmQ3NDU= # en Base64
  API_BACKEND: aHR0cHM6Ly9jdWRkbHktd2FkZGxlLXBqZzY3N3d2cDc0djNyNWdnLTgwODUuYXBwLmdpdGh1Yi5kZXYvYXBpL3Byb2R1Y3Rvcw==
  #DATABASE_URL: ${DATABASE_URL}   # en Base64
  #DATABASE_USERNAME: ${DATABASE_USERNAME}   # en Base64
  #DATABASE_PASSWORD: ${DATABASE_PASSWORD}   # en Base64
  #API_KEY: ${API_KEY}   # en Base64

#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode