# 4kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: melissa
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXNub3d5LXJpY2UtYTRzbnJhM2wudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvZGJfY2hhdGdwdD9zc2xtb2RlPXJlcXVpcmU=    # en Base64
  DATABASE_USERNAME: ZGJfY2hhdGdwdF9vd25lcg==   # en Base64
  DATABASE_PASSWORD: V2swN0RvUklhUW1Y  # en Base64
  RAPIDAPI_KEY: MmNiNjMyYjJjOW1zaDc0OTNhNWFmZmM2ODNlOXAxZDFmYzNqc241ZjdmNmRiYmQ3NDU= # en Base64
  API_BACKEND: aHR0cHM6Ly9zdXByZW1lLXNwYWNlLWJyb2Njb2xpLXB2eHg5cnh4NGd4YzZ2NjctODA4NS5hcHAuZ2l0aHViLmRldi9hcGk=
  #DATABASE_URL: ${DATABASE_URL}   # en Base64
  #DATABASE_USERNAME: ${DATABASE_USERNAME}   # en Base64
  #DATABASE_PASSWORD: ${DATABASE_PASSWORD}   # en Base64
  #API_KEY: ${API_KEY}   # en Base64

#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode