# kubectl apply -f service.yml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: melissa
spec:
  type: NodePort      
  ports:
  - port: 30001
    targetPort: 8085  
    nodePort: 30001
  selector:
    app: backend 